version: "3"
services:
    db:
        image: postgres:13.1
        environment:
            - POSTGRES_USER=$DB_USER
            - POSTGRES_PASSWORD=$DB_PASSWORD
        ports:
            - $DB_PORT:$DB_PORT
        command: -p $DB_PORT
    backend:
        depends_on:
            - db
        build: ./cvwo_server
        environment:
            - PORT=$DB_PORT
            - DB_HOST=db
            - DB_PORT=$DB_PORT
            - DB_USER=$DB_USER
            - DB_PASSWORD=$DB_PASSWORD
            - DB_DATABASE=$DB_NAME
            - JWT_SECRET=$JWT_SECRET
        ports:
            - $BACKEND_PORT:$BACKEND_PORT
    frontend:
        build: .
        environment:
            - PORT=$FRONTEND_PORT
        ports:
            - $FRONTEND_PORT:$FRONTEND_PORT
